# theme = "dark_plus"
theme = "darker_plus"

[editor]
cursorline = true
color-modes = true
line-number = "relative"

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.whitespace.characters]
tabpad = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
tab = ["rotate_view"]

